# Generated by Django 4.0.2 on 2022-04-05 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cassess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assess_number', models.CharField(max_length=6, null=True)),
                ('due_date', models.CharField(max_length=1, null=True)),
                ('publish_date', models.CharField(max_length=1, null=True)),
                ('question', models.CharField(max_length=1000, null=True)),
                ('question_format', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course', models.CharField(max_length=40, null=True)),
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4, null=True)),
                ('semester', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('type', models.CharField(blank=True, choices=[('pro', 'professor'), ('stu', 'student')], default=None, max_length=3, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='siteusers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=40, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.course')),
                ('memebers', models.ManyToManyField(to='peerAssessmentApp.SiteUsers')),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SiteUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.siteusers')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.course')),
            ],
        ),
    ]
