# Generated by Django 4.0.1 on 2022-03-18 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peerAssessmentApp', '0002_course_professor_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SiteUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.siteusers')),
            ],
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.CharField(default=1234, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(default=1234, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.CharField(default=123, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.course'),
        ),
        migrations.AddField(
            model_name='courseregistry',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.course'),
        ),
        migrations.AddField(
            model_name='courseregistry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
