# Generated by Django 3.2.12 on 2022-04-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessmentApp', '0002_auto_20220405_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteusers',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
