# Generated by Django 4.0.1 on 2022-03-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessmentApp', '0003_courseregistry_enrollment_delete_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
