# Generated by Django 3.2.12 on 2022-04-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessmentApp', '0003_siteusers_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteusers',
            old_name='type',
            new_name='types',
        ),
    ]
