# Generated by Django 3.2.12 on 2022-04-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessmentApp', '0004_rename_type_siteusers_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassess',
            name='question_format',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
