# Generated by Django 4.0.1 on 2022-03-24 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessmentApp', '0005_registry_delete_courseregistry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=40, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.course')),
                ('memebers', models.ManyToManyField(to='peerAssessmentApp.SiteUsers')),
            ],
        ),
    ]
