# Generated by Django 3.2.12 on 2022-04-12 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessmentApp', '0005_alter_cassess_question_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cassess',
            name='question',
        ),
        migrations.RemoveField(
            model_name='cassess',
            name='question_format',
        ),
        migrations.AddField(
            model_name='cassess',
            name='course',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.course'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, max_length=255)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.cassess')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.siteusers')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.cassess'),
        ),
        migrations.CreateModel(
            name='MCResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc', models.CharField(blank=True, choices=[('2', 'Disagree'), ('5', 'Strongly Agree'), ('4', 'Agree'), ('3', 'Neutral'), ('1', 'Strongly Disagree')], max_length=20)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.cassess')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.siteusers')),
            ],
        ),
    ]
