# Generated by Django 3.2.12 on 2022-03-30 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessmentApp', '0006_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteusers',
            name='type',
            field=models.CharField(blank=True, choices=[('pro', 'professor'), ('stu', 'student')], default=None, max_length=3, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.course'),
        ),
    ]
