# Generated by Django 3.2.12 on 2022-04-12 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessmentApp', '0007_alter_mcresponse_mc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassess',
            name='course',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.course'),
        ),
        migrations.AlterField(
            model_name='mcresponse',
            name='mc',
            field=models.CharField(blank=True, choices=[('2', 'Disagree'), ('3', 'Neutral'), ('5', 'Strongly Agree'), ('1', 'Strongly Disagree'), ('4', 'Agree')], max_length=20),
        ),
    ]
