# Generated by Django 3.2.12 on 2022-03-30 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peerAssessmentApp', '0007_auto_20220330_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteusers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='siteusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
