# Generated by Django 3.2.12 on 2022-04-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessmentApp', '0008_auto_20220412_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
        migrations.AlterField(
            model_name='mcresponse',
            name='mc',
            field=models.CharField(blank=True, choices=[('4', 'Agree'), ('2', 'Disagree'), ('1', 'Strongly Disagree'), ('3', 'Neutral'), ('5', 'Strongly Agree')], max_length=20),
        ),
    ]
