# Generated by Django 3.2.12 on 2022-04-12 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessmentApp', '0009_auto_20220412_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcresponse',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='response',
            name='assessment',
        ),
        migrations.AlterField(
            model_name='mcresponse',
            name='mc',
            field=models.CharField(blank=True, choices=[('3', 'Neutral'), ('2', 'Disagree'), ('5', 'Strongly Agree'), ('1', 'Strongly Disagree'), ('4', 'Agree')], max_length=20),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satus', models.CharField(max_length=255)),
                ('answer', models.ManyToManyField(to='peerAssessmentApp.Response')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.cassess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.siteusers')),
            ],
        ),
    ]
