# Generated by Django 3.2.12 on 2022-04-15 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peerAssessmentApp', '0011_auto_20220415_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcresponse',
            name='mc',
            field=models.CharField(blank=True, choices=[('1', 'Strongly Disagree'), ('4', 'Agree'), ('5', 'Strongly Agree'), ('2', 'Disagree'), ('3', 'Neutral')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mcresponse',
            name='responder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='response',
            name='responder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
