# Generated by Django 3.2.12 on 2022-04-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessmentApp', '0012_auto_20220415_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcresponse',
            name='mc',
            field=models.CharField(blank=True, choices=[('5', 'Strongly Agree'), ('3', 'Neutral'), ('1', 'Strongly Disagree'), ('4', 'Agree'), ('2', 'Disagree')], max_length=20),
        ),
    ]
