# Generated by Django 3.2.12 on 2022-04-15 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessmentApp', '0013_alter_mcresponse_mc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcresponse',
            name='mc',
            field=models.CharField(blank=True, choices=[('3', 'Neutral'), ('2', 'Disagree'), ('5', 'Strongly Agree'), ('4', 'Agree'), ('1', 'Strongly Disagree')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mcresponse',
            name='responder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.siteusers'),
        ),
        migrations.AlterField(
            model_name='response',
            name='responder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.siteusers'),
        ),
    ]
