# Generated by Django 3.2.12 on 2022-04-20 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessmentApp', '0014_auto_20220415_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='answerMC',
            field=models.ManyToManyField(to='peerAssessmentApp.MCResponse'),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewee', to='peerAssessmentApp.siteusers'),
        ),
        migrations.AlterField(
            model_name='mcresponse',
            name='mc',
            field=models.CharField(blank=True, choices=[('4', 'Agree'), ('5', 'Strongly Agree'), ('3', 'Neutral'), ('2', 'Disagree'), ('1', 'Strongly Disagree')], max_length=20),
        ),
    ]
