# Generated by Django 4.0.3 on 2022-04-19 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peerAssessmentApp', '0015_rename_user_registry_professor_alter_mcresponse_mc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='course_name',
        ),
        migrations.AddField(
            model_name='course',
            name='admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='mcresponse',
            name='mc',
            field=models.CharField(blank=True, choices=[('2', 'Disagree'), ('4', 'Agree'), ('5', 'Strongly Agree'), ('1', 'Strongly Disagree'), ('3', 'Neutral')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
