# Generated by Django 4.0.3 on 2022-04-19 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peerAssessmentApp', '0016_rename_course_course_course_name_course_admins_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registry',
            old_name='professor',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='registry',
            old_name='course',
            new_name='course_id',
        ),
        migrations.AddField(
            model_name='course',
            name='access_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mcresponse',
            name='mc',
            field=models.CharField(blank=True, choices=[('1', 'Strongly Disagree'), ('2', 'Disagree'), ('5', 'Strongly Agree'), ('4', 'Agree'), ('3', 'Neutral')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
