# Generated by Django 4.0.3 on 2022-04-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessmentApp', '0017_rename_professor_registry_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='access_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mcresponse',
            name='mc',
            field=models.CharField(blank=True, choices=[('4', 'Agree'), ('1', 'Strongly Disagree'), ('5', 'Strongly Agree'), ('2', 'Disagree'), ('3', 'Neutral')], max_length=20),
        ),
    ]
