# Generated by Django 4.0.3 on 2022-04-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessmentApp', '0018_alter_course_access_code_alter_mcresponse_mc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(default='', related_name='students', to='peerAssessmentApp.siteusers'),
        ),
        migrations.AlterField(
            model_name='mcresponse',
            name='mc',
            field=models.CharField(blank=True, choices=[('1', 'Strongly Disagree'), ('5', 'Strongly Agree'), ('2', 'Disagree'), ('4', 'Agree'), ('3', 'Neutral')], max_length=20),
        ),
    ]
