# Generated by Django 4.0.3 on 2022-04-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessmentApp', '0018_alter_mcresponse_mc'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='peerAssessmentApp.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mcresponse',
            name='mc',
            field=models.CharField(blank=True, choices=[('5', 'Strongly Agree'), ('4', 'Agree'), ('1', 'Strongly Disagree'), ('2', 'Disagree'), ('3', 'Neutral')], max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='reviewee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='peerAssessmentApp.siteusers'),
        ),
    ]
