# Generated by Django 4.0.2 on 2022-05-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerAssessmentApp', '0019_submission_course_alter_mcresponse_mc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to='peerAssessmentApp.SiteUsers'),
        ),
        migrations.AlterField(
            model_name='mcresponse',
            name='mc',
            field=models.CharField(blank=True, choices=[('3', 'Neutral'), ('1', 'Strongly Disagree'), ('4', 'Agree'), ('2', 'Disagree'), ('5', 'Strongly Agree')], max_length=20),
        ),
    ]
